export const theme = {
  colors: {
    surface: '#f7f9ff',
    surfaceDim: '#d7dadf',
    surfaceBright: '#f7f9ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f1f4f9',
    surfaceContainer: '#ebeef3',
    surfaceContainerHigh: '#e5e8ee',
    surfaceContainerHighest: '#e0e3e8',
    onSurface: '#181c20',
    onSurfaceVariant: '#3f4941',
    inverseSurface: '#2d3135',
    inverseOnSurface: '#eef1f6',
    outline: '#6f7a70',
    outlineVariant: '#bfc9be',
    surfaceTint: '#176c40',
    primary: '#005931',
    onPrimary: '#ffffff',
    primaryContainer: '#217346',
    onPrimaryContainer: '#a4f5bd',
    inversePrimary: '#88d8a1',
    secondary: '#006d42',
    onSecondary: '#ffffff',
    secondaryContainer: '#74fcb3',
    onSecondaryContainer: '#007347',
    error: '#ba1a1a',
    onError: '#ffffff',
    background: '#f7f9ff',
    onBackground: '#181c20',
    surfaceVariant: '#e0e3e8',
  },
  typography: {
    headlineLg: { fontFamily: 'Inter', fontSize: 32, fontWeight: '700' as const, lineHeight: 40, letterSpacing: -0.64 },
    headlineLgMobile: { fontFamily: 'Inter', fontSize: 24, fontWeight: '700' as const, lineHeight: 32, letterSpacing: -0.24 },
    headlineMd: { fontFamily: 'Inter', fontSize: 20, fontWeight: '600' as const, lineHeight: 28 },
    bodyLg: { fontFamily: 'Inter', fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
    bodySm: { fontFamily: 'Inter', fontSize: 14, fontWeight: '400' as const, lineHeight: 20 },
    labelMd: { fontFamily: 'Inter', fontSize: 12, fontWeight: '600' as const, lineHeight: 16, letterSpacing: 0.6 },
  },
  rounded: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  spacing: {
    base: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    marginMobile: 16,
    gutterMobile: 12,
  },
  shadows: {
    level1: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    level2: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
  }
};
